<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // 1.0
      // const p = Promise.resolve('lalala 001');
      // p.then(res => {
      //   console.log('res :>> ', res);
      // }).catch(err => {
      //   console.log('err :>> ', err);
      // }).finally(()=>{
      //   console.log('Promise finally...');
      // });
      // console.log('lalala 002');

      // 2.0
      // let promise = Promise.resolve();
      // promise.then(() => alert('promise done!'));
      // alert('code finished'); // 这个 alert 先显示

      // 3.0
      // 如果一个 promise 的 error 未被在微任务队列的末尾进行处理，则会出现“未处理的 rejection”。
      // let promise = Promise.reject(new Error('what the fuck!!!'));

      // // promise.catch(error => {
      // //   console.log('catch error :>> ', error);
      // // });

      // setTimeout(() => {
      //   promise.catch(error => {
      //     console.log('catch error *** :>> ', error);
      //   });
      // }, 0);

      // //忘记加catch情况下执行下面的事件监听
      // window.addEventListener('unhandledrejection', event => {
      //   console.log('event.reason ### :>> ', event.reason);
      // });

      //4.0 async/await
      // async function run(params) {
      //   let promise1 = new Promise((resolve, reject) => {
      //     setTimeout(() => {
      //       console.log('000003 -- Promise');
      //       return resolve('resolve');
      //     }, 2000);
      //   });
      //   let promise2 = new Promise((resolve, reject) => {
      //     setTimeout(() => {
      //       console.log('000001 -- Promise');
      //       return reject(new Error('reject'));
      //     }, 1000);
      //   });

      //   await promise2.then(res2 => console.log(res2)).catch(err2 => console.log(err2));
      //   console.log('000002');
      //   await promise1.then(res1 => console.log(res1)).catch(err1 => console.log(err1));
      //   console.log('000004');
      // }

      //5.0 图片链接识别
      function checkImage(url) {
        return new Promise((resolve, reject) => {
          const img = document.createElement('img');
          img.src = url;
          img.onload = res => {
            console.log('onload res :>> ', res);
            resolve(res);
          };
          img.onerror = err => {
            console.log('onerror err :>> ', err);
            reject(err);
          };
        });
      }

      checkImage('https://wangdoc.com/es6/images/cover_thumbnail_3rd.jpg')
        .then(res => {
          alert('有效图片链接');
          console.log('then res :>> ', res);
          console.log('res.path :>> ', res.path);
          res.path.forEach(element => {
            console.log('element :>> ', element);
            document.body.append(element);
          });
        })
        .catch(err => {
          alert('无效图片链接');
          console.log('catch err :>> ', err);
        });
    </script>
  </body>
</html>
